#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 || $# -gt 2 ]]; then
  echo "usage: perf_baseline.sh <holyc-bin> [out-file]" >&2
  exit 2
fi

HOLYC_BIN="$1"
OUT_FILE="${2:-docs/perf-baseline.md}"

measure_seconds() {
  local label="$1"
  shift
  if command -v python3 >/dev/null 2>&1; then
    local seconds
    seconds="$(
      python3 - "$@" <<'PY'
import subprocess
import sys
import time

start = time.perf_counter()
subprocess.run(sys.argv[1:], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
elapsed = time.perf_counter() - start
print(f"{elapsed:.6f}")
PY
    )"
    echo "${label}|${seconds}"
    return
  fi

  local tmp
  tmp="$(mktemp)"
  /usr/bin/time -p "$@" >/dev/null 2>"${tmp}"
  local seconds
  seconds="$(awk '$1=="real" {print $2}' "${tmp}")"
  rm -f "${tmp}"
  echo "${label}|${seconds}"
}

CHECK_RESULT="$(measure_seconds check "${HOLYC_BIN}" check tests/samples/features.HC)"
EMIT_RESULT="$(measure_seconds emit_llvm "${HOLYC_BIN}" emit-llvm tests/samples/llvm.HC)"
JIT_RESULT="$(measure_seconds jit "${HOLYC_BIN}" jit tests/samples/jit.HC)"

CHECK_SEC="${CHECK_RESULT#*|}"
EMIT_SEC="${EMIT_RESULT#*|}"
JIT_SEC="${JIT_RESULT#*|}"

{
  echo "# Performance Baseline"
  echo
  echo "Generated by scripts/perf_baseline.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")."
  echo
  echo "All timings are wall-clock seconds on the local host."
  echo "Timer source: Python monotonic high-resolution clock when available, otherwise /usr/bin/time -p."
  echo
  echo "| Operation | Sample | Seconds |"
  echo "| --- | --- | ---: |"
  echo "| check | tests/samples/features.HC | ${CHECK_SEC} |"
  echo "| emit-llvm | tests/samples/llvm.HC | ${EMIT_SEC} |"
  echo "| jit | tests/samples/jit.HC | ${JIT_SEC} |"
} >"${OUT_FILE}"

echo "wrote ${OUT_FILE}"
