#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<'EOF'
usage: perf_opt_sweep.sh <holyc-bin> [out-file] [options]

Positional arguments:
  <holyc-bin>               Path to holyc binary.
  [out-file]                Optional markdown output path (legacy alias for --out-md).

Options:
  --out-md <path>           Markdown summary path (default: .holyc-artifacts/perf-opt-sweep.md)
  --suite <name>            all|compile|runtime (default: all)
  --runs <count>            Timed runs per benchmark (default: 3)
  --warmup <count>          Warmup runs per benchmark (default: 1)
  -h, --help                Show this help.
EOF
}

HOLYC_BIN=""
OUT_MD=".holyc-artifacts/perf-opt-sweep.md"
SUITE="all"
RUNS="3"
WARMUP="1"
POSITIONAL_OUT_SEEN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    --out-md)
      if [[ $# -lt 2 ]]; then
        echo "error: --out-md requires a value" >&2
        exit 2
      fi
      OUT_MD="$2"
      shift 2
      ;;
    --out-md=*)
      OUT_MD="${1#*=}"
      shift
      ;;
    --suite)
      if [[ $# -lt 2 ]]; then
        echo "error: --suite requires a value" >&2
        exit 2
      fi
      SUITE="$2"
      shift 2
      ;;
    --suite=*)
      SUITE="${1#*=}"
      shift
      ;;
    --runs)
      if [[ $# -lt 2 ]]; then
        echo "error: --runs requires a value" >&2
        exit 2
      fi
      RUNS="$2"
      shift 2
      ;;
    --runs=*)
      RUNS="${1#*=}"
      shift
      ;;
    --warmup)
      if [[ $# -lt 2 ]]; then
        echo "error: --warmup requires a value" >&2
        exit 2
      fi
      WARMUP="$2"
      shift 2
      ;;
    --warmup=*)
      WARMUP="${1#*=}"
      shift
      ;;
    --)
      shift
      break
      ;;
    -*)
      echo "error: unknown option: $1" >&2
      usage
      exit 2
      ;;
    *)
      if [[ -z "${HOLYC_BIN}" ]]; then
        HOLYC_BIN="$1"
      elif [[ ${POSITIONAL_OUT_SEEN} -eq 0 ]]; then
        OUT_MD="$1"
        POSITIONAL_OUT_SEEN=1
      else
        echo "error: unexpected argument: $1" >&2
        usage
        exit 2
      fi
      shift
      ;;
  esac
done

if [[ $# -gt 0 ]]; then
  echo "error: unexpected trailing arguments: $*" >&2
  usage
  exit 2
fi

if [[ -z "${HOLYC_BIN}" ]]; then
  usage
  exit 2
fi
if ! [[ "${SUITE}" =~ ^(all|compile|runtime)$ ]]; then
  echo "error: --suite must be one of: all, compile, runtime" >&2
  exit 2
fi
if ! [[ "${RUNS}" =~ ^[1-9][0-9]*$ ]]; then
  echo "error: --runs must be a positive integer" >&2
  exit 2
fi
if ! [[ "${WARMUP}" =~ ^[0-9]+$ ]]; then
  echo "error: --warmup must be a non-negative integer" >&2
  exit 2
fi
if ! command -v python3 >/dev/null 2>&1; then
  echo "error: python3 is required" >&2
  exit 2
fi

mkdir -p "$(dirname "${OUT_MD}")"

TEMP_DIR="$(mktemp -d)"
cleanup() {
  rm -rf "${TEMP_DIR}"
}
trap cleanup EXIT

for level in 0 1 2 3 s z; do
  ./scripts/perf_baseline.sh "${HOLYC_BIN}" \
    --suite "${SUITE}" \
    --opt-level "${level}" \
    --runs "${RUNS}" \
    --warmup "${WARMUP}" \
    --out-md "${TEMP_DIR}/${level}.md" \
    --out-json "${TEMP_DIR}/${level}.json" \
    >/dev/null
done

python3 - "${TEMP_DIR}" "${OUT_MD}" "${SUITE}" "${RUNS}" "${WARMUP}" <<'PY'
import datetime
import json
import pathlib
import sys

root = pathlib.Path(sys.argv[1])
out_md = pathlib.Path(sys.argv[2])
suite = sys.argv[3]
runs = int(sys.argv[4])
warmup = int(sys.argv[5])

levels = ["0", "1", "2", "3", "s", "z"]
rows = []
for level in levels:
    data = json.loads((root / f"{level}.json").read_text())
    compile_sum = 0.0
    runtime_sum = 0.0
    total_sum = 0.0
    for bench in data["benchmarks"]:
        med = bench["summary"]["median_sec"]
        total_sum += med
        if bench["suite"] == "compile":
            compile_sum += med
        elif bench["suite"] == "runtime":
            runtime_sum += med
    rows.append(
        {
            "level": level,
            "compile_sum": compile_sum,
            "runtime_sum": runtime_sum,
            "total_sum": total_sum,
        }
    )

best_total = min(row["total_sum"] for row in rows)

generated_at = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
lines = [
    "# Perf Opt-Level Sweep",
    "",
    f"Generated by scripts/perf_opt_sweep.sh on {generated_at}.",
    "",
    f"Suite: {suite}. Runs: {runs}. Warmup: {warmup}.",
    "Sums are based on benchmark median seconds (lower is better).",
    "",
    "| Opt Level | Compile Median Sum (s) | Runtime Median Sum (s) | Total Median Sum (s) | Relative vs Best |",
    "| --- | ---: | ---: | ---: | ---: |",
]

for row in rows:
    rel = row["total_sum"] / best_total if best_total > 0 else 1.0
    lines.append(
        "| {level} | {compile_sum:.6f} | {runtime_sum:.6f} | {total_sum:.6f} | {rel:.3f}x |".format(
            **row, rel=rel
        )
    )

out_md.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {out_md}")
PY
